# LOGS SETTINGS
logs:
  level: "INFO" #  "DEBUG" / "INFO" / "WARNING" / "ERROR" / "CRITICAL"
  enable_log_save: true # true / false
  file: "logs/bot_logs.log"
  rotation_size: "50 MB" # B / KB / MB / GB / TB
# BOT SETTINGS
bot:
  users_to_ping:
    - 690334768185082295
  alerts_channel: 1199674370474397747
  announcement_monitoring_channel: 1199674616998789150
# METRICS SETTINGS
validator:
  prometheus_metrics_url: "http://<IP/DOMAIN>:9184/metrics" # MAKE SURE TO CHECK FIREWALL SETTINGS
